---
name: CPAN-Mini-ProjectDocs
version: 0.02.5
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
abstract: generates nice module documentation from you CPAN mini
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Tar: 0
  CPAN::PackageDetails: 0
  Digest::MD5: 0
  File::HomeDir: 0
  File::Slurp: 0
  Getopt::Long: 0
  Pod::Parser: 1.38
  Pod::ProjectDocs: 0
  Readonly: 0
  Sub::Exporter: 0
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Text::Diff: 0
provides:
  CPAN::Mini::ProjectDocs:
    file: lib/CPAN/Mini/ProjectDocs.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
